name: meals_world
description: Meals world app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  equatable: ^2.0.5
  go_router: ^11.1.2

  meals_api:
    path: packages/meals_api

  meals_repository:
    path: packages/meals_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.3
  bloc_test: ^9.1.4
  mocktail: ^1.0.1

flutter:

  uses-material-design: true
